repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args:
          - --fix
          - --config=./.ruff.toml
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.0
    hooks:
      - id: pyproject-fmt
        files: (^|/)pyproject\.toml$
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
